tcc -impdef libFLAC-8.dll
move libFLAC-8.dll C:\Dev\tcc\lib\
tcc -impdef libfreetype-6.dll
move libfreetype-6.dll C:\Dev\tcc\lib\
tcc -impdef libjpeg-9.dll
move libjpeg-9.dll C:\Dev\tcc\lib\
tcc -impdef libmodplug-1.dll
move libmodplug-1.dll C:\Dev\tcc\lib\
tcc -impdef libmpg123-0.dll
move libmpg123-0.dll C:\Dev\tcc\lib\
tcc -impdef libogg-0.dll
move libogg-0.dll C:\Dev\tcc\lib\
tcc -impdef libopus-0.dll
move libopus-0.dll C:\Dev\tcc\lib\
tcc -impdef libopusfile-0.dll
move libopusfile-0.dll C:\Dev\tcc\lib\
tcc -impdef libpng16-16.dll
move libpng16-16.dll C:\Dev\tcc\lib\
tcc -impdef libtiff-5.dll
move libtiff-5.dll C:\Dev\tcc\lib\
tcc -impdef libvorbis-0.dll
move libvorbis-0.dll C:\Dev\tcc\lib\
tcc -impdef libvorbisfile-3.dll
move libvorbisfile-3.dll C:\Dev\tcc\lib\
tcc -impdef libwebp-7.dll
move libwebp-7.dll C:\Dev\tcc\lib\
tcc -impdef SDL2.dll
move SDL2.dll C:\Dev\tcc\lib\
tcc -impdef SDL2.lib
move SDL2.lib C:\Dev\tcc\lib\
tcc -impdef SDL2_image.dll
move SDL2_image.dll C:\Dev\tcc\lib\
tcc -impdef SDL2_image.lib
move SDL2_image.lib C:\Dev\tcc\lib\
tcc -impdef SDL2_mixer.dll
move SDL2_mixer.dll C:\Dev\tcc\lib\
tcc -impdef SDL2_mixer.lib
move SDL2_mixer.lib C:\Dev\tcc\lib\
tcc -impdef SDL2_net.dll
move SDL2_net.dll C:\Dev\tcc\lib\
tcc -impdef SDL2_net.lib
move SDL2_net.lib C:\Dev\tcc\lib\
tcc -impdef SDL2_ttf.dll
move SDL2_ttf.dll C:\Dev\tcc\lib\
tcc -impdef SDL2_ttf.lib
move SDL2_ttf.lib C:\Dev\tcc\lib\
tcc -impdef SDL2main.lib
move SDL2main.lib C:\Dev\tcc\lib\
tcc -impdef zlib1.dll
move zlib1.dll C:\Dev\tcc\lib\